apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-earth
spec:
  selector:
    matchLabels:
      planet: earth
  replicas: 1
  template:
    metadata:
      labels:
        planet: earth
    spec:
      containers:
        - name: hello-earth
          image: stanleynguyen/hello-earth
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: hello-earth
spec:
  selector:
    planet: earth
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
