apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-jupiter
spec:
  selector:
    matchLabels:
      planet: jupiter
  replicas: 1
  template:
    metadata:
      labels:
        planet: jupiter
    spec:
      containers:
        - name: hello-jupiter
          image: stanleynguyen/hello-jupiter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: hello-jupiter
spec:
  selector:
    planet: jupiter
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
